---
- name : Test play book to try and gather facts from host var file
  hosts: juniper
  gather_facts: True

  tasks:
      - name : Debug test1 
        debug: 
            var: hostvars[inventory_hostname]
        tags: test1

      - name: Debug test2
        debug: 
            var: ansible_net_model
            #when: ansible_net_model == "ex4300"
        when: "'ex4300' in ansible_net_model"
        tags: test2

      - name: Debug test3
        debug: 
            msg: "{{ansible_net_version}}"
        when:  "'15.5' in anisble_net_version"
        tags: test3

      - name: Debug test4
        debug: 
            msg: "my name is anthony gonzales"
        tags: test4



