
---
- name: Install Junos OS
  hosts: juniper
  connection: local
  gather_facts: no

  vars:
    OS_version: "21.2R3.8"
    OS_package: "jinstall-ex-4300-21.2R3.8-signed.tgz"
    pkg_dir: "~/sw_images"
    log_dir: "{{ playbook_dir }}"
    netconf_port: 830
    wait_time: 3600

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: "{{ netconf_port }}"
        timeout: 5

    - name: Install Junos OS package
      juniper.device.software:
        version: "{{ OS_version }}"
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        reboot: True
        validate: True
        logfile: "{{ log_dir }}/software.log"
      register: response
      notify:
      - wait_reboot

    - name: Print response
      debug:
        var: response

  handlers:
    - name: wait_reboot
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
      when: not response.check_mode
