---

- name: Install Junos OS
  hosts: juniper
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    wait_time: 3600
    pkg_dir: /home/vigneshn/sw_images
    OS_version: 21.2R3.8
    OS_package: jinstall-ex-4300-21.2R3.8-signed.tgz
    log_dir: /home/vigneshn/ansible_scripts

 

  vars_prompt:
          - name: USERNAME
            prompt: User name
            private: no
          - name: DEVICE_PASSWORD
            prompt: Device password
            private: yes

 

  tasks:
          - name: Checking NETCONF connectivity
            wait_for: host={{ inventory_hostname }} port=830 timeout=5
          - name: Install Junos OS package
            juniper_junos_software:
                    host={{ inventory_hostname }}
                    user={{ USERNAME }}
                    passwd={{ DEVICE_PASSWORD }}
                    reboot=yes
                    version={{ OS_version }}
                    package={{ pkg_dir }}/{{ OS_package }}
                    logfile={{ log_dir }}/software.log
            register: sw
            notify:
                    - wait_reboot
  handlers:
          - name: wait_reboot
            wait_for: host={{ inventory_hostname }} port=830 timeout={{ wait_time }}
            when: not sw.check_mode 
