
--- 
- 
  connection: local
  gather_facts: false
  handlers: 
    - 
      name: wait_reboot
      wait_for: "host={{ inventory_hostname }} port=830 timeout={{ wait_time }}"
      when: "not sw.check_mode"
  hosts: juniper
  name: "Install Junos OS"
  roles: 
    - Juniper.junos
  tasks: 
    - 
      name: "Checking NETCONF connectivity"
      wait_for: "host={{ inventory_hostname }} port=830 timeout=5"
    - 
      junos_install_os:
          host={{ inventory_hostname }}
          user={{ USERNAME }}
          passwd={{ DEVICE_PASSWORD }}
          reboot=yes
          version={{ OS_version }}
          package={{ pkg_dir }}/{{ OS_package }}
          logfile={{ log_dir }}/software.log
      name: "Install Junos OS package"
      notify: 
        - wait_reboot
      register: sw
  vars: 
    OS_package: jinstall-ex-4300-21.2R3.8-signed.tgz
    OS_version: 21.2R3.8
    log_dir: /home/vigneshn/ansible_files
    pkg_dir: /home/vigneshn/sw_images
    wait_time: 3600
  vars_prompt: 
    - 
      name: USERNAME
      private: false
      prompt: "User name"
    - 
      name: DEVICE_PASSWORD
      private: true
      prompt: "Device password"


