from pprint import pprint

dic_exp =  {"changed": false, "stdout": ["fpc0:\n--------------------------------------------------------------------------\nFilesystem              Size       Used      Avail  Capacity   Mounted on\n/dev/da0s1a             316M       290M       640K      100%  /\ndevfs                   1.0K       1.0K         0B      100%  /dev\n/dev/md0                412M       412M         0B      100%  /packages/mnt/junos\n/dev/md1                6.7M       2.1M       4.1M       33%
/packages/mfs-fips-mode-powerpc\n/dev/md2                5.5M       5.5M         0B      100%  /packages/mnt/fips-mode-powerpc-21.3R2.11\n/dev/md3                7.7M       3.1M       4.0M       44%  /packages/mfs-jcrypto-ex\n/dev/md4                8.5M       8.5M         0B      100%  /packages/mnt/jcrypto-ex-21.3R2.11\n/dev/md5                9.2M       4.5M       3.9M       54%  /packages/mfs-jdocs-ex\n/dev/md6                 13M        13M         0B      100%
/packages/mnt/jdocs-ex-21.3R2.11\n/dev/md7                7.7M       3.1M       4.0M       44%  /packages/mfs-jphone-home\n/dev/md8                9.3M       9.3M         0B      100%  /packages/mnt/jphone-home-21.3R2.11\n/dev/md9                6.3M       1.6M       4.2M       28%  /packages/mfs-jsd\n/dev/md10               5.5M       5.5M         0B      100%  /packages/mnt/jsd-powerpc-21.3R2.11-jet-1\n/dev/md11                11M       6.7M       3.7M       64%
/packages/mfs-jsdn-powerpc\n/dev/md12               6.6M       6.6M         0B      100%  /packages/mnt/jsdn-powerpc-21.3R2.11\n/dev/md13               110M        98M       3.8M       96%  /packages/mfs-junos-ex-4300\n/dev/md14               254M       254M         0B      100%  /packages/mnt/junos-ex-4300-21.3R2.11\n/dev/md15                16M        11M       3.2M       78%  /packages/mfs-jweb-ex\n/dev/md16                34M        34M         0B      100%
/packages/mnt/jweb-ex-21.3R2.11\n/dev/md17                11M       6.0M       3.8M       61%  /packages/mfs-py-base-powerpc\n/dev/md18                17M        17M         0B      100%  /packages/mnt/py-base-powerpc-21.3R2.11\n/dev/md19               9.0M       4.4M       3.9M       53%  /packages/mfs-py-extensions-powerpc\n/dev/md20                14M        14M         0B      100%  /packages/mnt/py-extensions-powerpc-21.3R2.11\n/dev/md21               9.2M       4.6M       3.9M
                                         54%  /packages/mfs-restapi-ex\n/dev/md22                12M        12M         0B      100%  /packages/mnt/restapi-ex-21.3R2.11\n/dev/da0s3e             170M        22M       135M       14%  /var\n/dev/md23               252M        14K       232M        0%  /tmp\n/dev/da0s3d             887M        98M       718M       12%  /var/tmp\n/dev/da0s4d             116M       102K       106M        0%  /config\n/dev/md24               236M
                                         102M       115M       47%  /var/rundb\nprocfs                  4.0K       4.0K         0B      100%  /proc\n/var/jail/etc           170M        22M       135M       14%  /packages/mnt/jweb-ex-21.3R2.11/jail/var/etc\n/var/jail/run           170M        22M       135M       14%  /packages/mnt/jweb-ex-21.3R2.11/jail/var/run\n/var/jail/tmp           170M        22M       135M       14%  /packages/mnt/jweb-ex-21.3R2.11/jail/var/tmp\n/var/tmp
                                         887M        98M       718M       12%  /packages/mnt/jweb-ex-21.3R2.11/jail/var/tmp/uploads\n/var/jail/sess          170M        22M       135M       14%  /packages/mnt/jweb-ex-21.3R2.11/jail/var/sess\n/var/jail/log           170M        22M       135M       14%  /packages/mnt/jweb-ex-21.3R2.11/jail/var/log\ndevfs                   1.0K       1.0K         0B      100%  /packages/mnt/jweb-ex-21.3R2.11/jail/dev\n/var/jail/jweb-app       170M        22M
                                         135M      14%  /packages/mnt/jweb-ex-21.3R2.11/jail/var/jweb-app\n/var/jails/rest-api       170M        22M       135M     14%  /packages/mnt/restapi-ex-21.3R2.11/web-api/var\ndevfs                   1.0K       1.0K         0B      100%  /packages/mnt/restapi-ex-21.3R2.11/web-api/dev\n/dev/md25               6.7M       2.1M       4.1M       33%  /packages/mfs-fips-mode-powerpc\n/dev/md26               7.7M       3.1M       4.0M       44%
                                         /packages/mfs-jcrypto-ex\n/dev/md27               9.2M       4.5M       3.9M       54%  /packages/mfs-jdocs-ex\n/dev/md28               7.7M       3.1M       4.0M       44%  /packages/mfs-jphone-home\n/dev/md29               6.3M       1.6M       4.2M       28%  /packages/mfs-jsd\n/dev/md30                11M       6.7M       3.7M       64%  /packages/mfs-jsdn-powerpc\n/dev/md31               110M        98M       3.8M       96%
                                         /packages/mfs-junos-ex-4300\n/dev/md32                16M        11M       3.2M       78%  /packages/mfs-jweb-ex\n/dev/md33                11M       6.0M       3.8M       61%  /packages/mfs-py-base-powerpc\n/dev/md34               9.0M       4.4M       3.9M       53%  /packages/mfs-py-extensions-powerpc\n/dev/md35               9.2M       4.6M       3.9M       54%  /packages/mfs-restapi-ex"], "stdout_lines": [["fpc0:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "--------------------------------------------------------------------------",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "Filesystem              Size       Used
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Avail  Capacity   Mounted on", "/dev/da0s1a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       316M       290M       640K      100%  /",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "devfs                   1.0K       1.0K
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%  /dev", "/dev/md0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       412M       412M         0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/junos", "/dev/md1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       6.7M       2.1M       4.1M       33%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mfs-fips-mode-powerpc", "/dev/md2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       5.5M       5.5M         0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/fips-mode-powerpc-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md3                7.7M       3.1M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       4.0M       44%  /packages/mfs-jcrypto-ex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md4                8.5M       8.5M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jcrypto-ex-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md5                9.2M       4.5M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3.9M       54%  /packages/mfs-jdocs-ex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md6                 13M        13M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jdocs-ex-21.3R2.11", "/dev/md7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       7.7M       3.1M       4.0M       44%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mfs-jphone-home", "/dev/md8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       9.3M       9.3M         0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jphone-home-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md9                6.3M       1.6M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       4.2M       28%  /packages/mfs-jsd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md10               5.5M       5.5M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jsd-powerpc-21.3R2.11-jet-1",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md11                11M       6.7M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3.7M       64%  /packages/mfs-jsdn-powerpc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md12               6.6M       6.6M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jsdn-powerpc-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md13               110M        98M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3.8M       96%  /packages/mfs-junos-ex-4300",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md14               254M       254M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/junos-ex-4300-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md15                16M        11M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3.2M       78%  /packages/mfs-jweb-ex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md16                34M        34M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11", "/dev/md17
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       11M       6.0M       3.8M       61%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mfs-py-base-powerpc", "/dev/md18
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       17M        17M         0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/py-base-powerpc-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md19               9.0M       4.4M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3.9M       53%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mfs-py-extensions-powerpc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md20                14M        14M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/py-extensions-powerpc-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md21               9.2M       4.6M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3.9M       54%  /packages/mfs-restapi-ex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/md22                12M        12M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/restapi-ex-21.3R2.11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/da0s3e             170M        22M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       135M       14%  /var", "/dev/md23
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       252M        14K       232M        0%  /tmp",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/dev/da0s3d             887M        98M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       718M       12%  /var/tmp", "/dev/da0s4d
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       116M       102K       106M        0%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /config", "/dev/md24               236M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       102M       115M       47%  /var/rundb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "procfs                  4.0K       4.0K
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%  /proc", "/var/jail/etc
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       170M        22M       135M       14%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/var/etc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/var/jail/run           170M        22M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       135M       14%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/var/run",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/var/jail/tmp           170M        22M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       135M       14%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/var/tmp",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/var/tmp                887M        98M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       718M       12%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/var/tmp/uploads",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/var/jail/sess          170M        22M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       135M       14%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/var/sess",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/var/jail/log           170M        22M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       135M       14%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/var/log",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "devfs                   1.0K       1.0K
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/dev",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/var/jail/jweb-app       170M        22M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       135M      14%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/jweb-ex-21.3R2.11/jail/var/jweb-app",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "/var/jails/rest-api       170M        22M
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       135M     14%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/restapi-ex-21.3R2.11/web-api/var",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "devfs                   1.0K       1.0K
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0B      100%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /packages/mnt/restapi-ex-21.3R2.11/web-api/dev",
            "/dev/md25               6.7M       2.1M       4.1M       33%  /packages/mfs-fips-mode-powerpc", "/dev/md26               7.7M       3.1M       4.0M       44%  /packages/mfs-jcrypto-ex", "/dev/md27               9.2M       4.5M       3.9M       54%  /packages/mfs-jdocs-ex", "/dev/md28               7.7M       3.1M       4.0M       44%  /packages/mfs-jphone-home", "/dev/md29               6.3M       1.6M       4.2M       28%  /packages/mfs-jsd", "/dev/md30                11M
            6.7M       3.7M       64%  /packages/mfs-jsdn-powerpc", "/dev/md31               110M        98M       3.8M       96%  /packages/mfs-junos-ex-4300", "/dev/md32                16M        11M       3.2M       78%  /packages/mfs-jweb-ex", "/dev/md33                11M       6.0M       3.8M       61%  /packages/mfs-py-base-powerpc", "/dev/md34               9.0M       4.4M       3.9M       53%  /packages/mfs-py-extensions-powerpc", "/dev/md35               9.2M       4.6M       3.9M
            54%  /packages/mfs-restapi-ex"]]}

pprint(dic_exp)
