---
- name : Playbook to test loops using the host file to see how loops funtion
  hosts: local
  gather_facts: False
  vars:
      i: i
      net_devices:
          - [["rtr1",["a","b","c"]], "rtr2", "rtr3"]
          - ["sw1", "sw2", "sw3"]

  tasks:
      - name: use old format of loop and test list flattening 
        debug: 
            var: item
        with_items: "{{net_devices}}"

      - name: use old format of loop and prevent list flattening
        debug:
            var: item
        with_list: "{{net_devices}}"

      - name: use new format of loop and there is no list flattening
        debug:
            var: i
        loop: "{{net_devices}}"
        #loop: "{{sf2_row3}}"

      - name: vignesh's test with loops
        debug:
            msg: "{{item[0]}} is the list element selected"
        loop: "{{net_devices[0]}}"


