---
- name: Test loop over a dictionary variable
  hosts: local
  gather_facts: False
  vars: 
    hogwarts:
        gryfinddor: ["harry", "ron", "hermoine"]
        ravenclaw: ["padama", "cho", "luna"]
        huffelpuff: ["Cedric","tonks", "Justin"]
        slytherin: ["malfoy", "snape", "voldemort"]

  tasks:
      - name: loop through a dictornary variable
        debug:
            #var: item.key ==> item.value
            msg: "{{item.key}} = {{item.value}}"
        loop: "{{hogwarts|dict2items}}"

      - name: just print the data structure from playbook
        debug:
            var: hogwarts

      - name: now try a condition while looping thro data struct
        debug:
            msg: "{{item.value}} is the best character in {{item.key}}"
        loop: "{{hogwarts|dict2items}}"
        when: item.value[0] == 'harry' or item.value[2] == 'luna' or item.value[0] == 'Cedric' or item.value[1] == 'snape'
        #with_nested: "{{hogwarts}}"

